# Generated by Django 2.2.7 on 2019-11-30 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component_option', '0002_manufacturingfirm'),
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Categorie', to='component_option.Categorie'),
            preserve_default=False,
        ),
    ]
