# Generated by Django 2.2.7 on 2019-11-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component_option', '0002_manufacturingfirm'),
        ('component', '0002_component_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='manufacturing_firm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Manufacturing_firm', to='component_option.ManufacturingFirm'),
            preserve_default=False,
        ),
    ]
