# Generated by Django 2.2.7 on 2019-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_component_manufacturing_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description',
            field=models.TextField(default='это'),
            preserve_default=False,
        ),
    ]
