# Generated by Django 2.2.7 on 2019-11-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0004_component_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
