# Generated by Django 2.2.7 on 2019-11-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0006_component_year_of_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='in_stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
