# Generated by Django 2.2.7 on 2019-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0007_component_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='rating',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
    ]
