# Generated by Django 2.2.7 on 2019-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0009_component_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
