# Generated by Django 2.2.7 on 2019-12-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_with_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
