# Generated by Django 2.2.7 on 2019-12-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.TextField(verbose_name='Адресс доставки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='card.Card', verbose_name='Корзина')),
            ],
        ),
    ]
